app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('addtask', views.addtask, name='addtask'),
    path('taskdetails', views.taskdetails, name='taskdetails'),
    path('leaderboard', views.leaderboard, name='leaderboard')
]

wakemeup/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

app/templates/app/addtask.html
{% extends 'app/layout.html' %}

{% block body %}

    <form action="{% url 'app:index' %}" method="post">
        {% csrf_token %}
        <input type="text">
        <button type="submit">Submit</button>
    </form>

{% endblock %}

app/templates/app/index.html
{% extends 'app/layout.html' %}

{% block body %}
    {% comment %} <a href="addtask">Post task and also change the class</a> {% endcomment %}
    
    <div class="container-fluid py-4">
        <div class="row align-items-md-stretch">
            {% for i in res %}
                <div class="col-md-14" style="padding-bottom: 3ch">
                    <div class="h-100 p-5 text-bg-dark rounded-4">
                        <h2><u><i>{{i.6}}</i></u></h2>
                        <p>{{i.1}}</p>
                        <a href="taskdetails"><button class="btn btn-outline-secondary" type="button">Details</button></a>
                    </div>
                </div>

                
                {% empty %}
                    <div class="h-100 p-5 text-bg-dark rounded-3">
                        No tasks to show
                    </div>

            {% endfor %}
        </div>
    </div>

{% endblock %}  

app/templates/app/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>TaskHub</title>
        {% load static %}
        {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" /> {% endcomment %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>
    <body>
        <header>
            <div class="px-3 py-2 text-bg-dark">
                <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                    <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
                    </a>
        
                    <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                    <li>
                        <a href="{% url 'index' %}" class="nav-link text-secondary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16"><path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/></svg>
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'app:leaderboard' %}" class="nav-link text-white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bar-chart-fill" viewBox="0 0 16 16"><path d="M1 11a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-3zm5-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2z"/></svg>
                            Leaderboard
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link text-white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hourglass-split" viewBox="0 0 16 16"><path d="M2.5 15a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1h-11zm2-13v1c0 .537.12 1.045.337 1.5h6.326c.216-.455.337-.963.337-1.5V2h-7zm3 6.35c0 .701-.478 1.236-1.011 1.492A3.5 3.5 0 0 0 4.5 13s.866-1.299 3-1.48V8.35zm1 0v3.17c2.134.181 3 1.48 3 1.48a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351z"/></svg>
                            History
                        </a>
                    </li>
                    </ul>
                </div>
                </div>
            </div>
            <div class="px-3 py-2 border-bottom mb-3">
                <div class="container d-flex flex-wrap justify-content-center">
                <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto" role="search">
                    <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
                </form>
        
                <div>
                    <a href="app/signup">
                        <button type="button" class="btn btn-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-add" viewBox="0 0 16 16"><path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/><path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z"/></svg>
                            Sign-up
                        </button>
                    </a>
                    <a href="app/login">
                        <button type="button" class="btn btn-secondary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-check" viewBox="0 0 16 16"><path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm1.679-4.493-1.335 2.226a.75.75 0 0 1-1.174.144l-.774-.773a.5.5 0 0 1 .708-.708l.547.548 1.17-1.951a.5.5 0 1 1 .858.514ZM11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/><path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z"/></svg>
                            Login
                        </button>
                    </a>
                </div>
                </div>
            </div>
          </header>  
        
        
        {% comment %} <div class="video-bg">
            <video playsinline autoplay muted loop>
                <source src="{% static 'asd.mp4'%}" type="video/mp4">
            </video>
        </div>         {% endcomment %}
        {% block body %}
        {% endblock %}
        
        <div class="container">
            <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
              <div class="col mb-3">
                <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                </a>
                <p class="text-muted">© WakeMeUp</p>
              </div>
          
              <div class="col mb-3">
          
              </div>
          
              <div class="col mb-3">
                <h5>Group Members</h5>
                <ul class="nav flex-column">
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">M. Awais Ahmad</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Talha Mumtaz</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Afaq Ali Saqib</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Ghulam Mujtaba</a></li>
                </ul>
              </div>
          
              <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
              </div>
          
              <div class="col mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                  <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
              </div>
            </footer>
        </div>

        {% comment %} <footer>
            <div class="about">
                <h3>Group Members</h3>
                <div>M. Afaq Ali Saqib</div>
                <div>M. Awais Ahmad</div>
                <div>Ghulam Mujtaba</div>
                <div>Talha Mumtaz</div>
            </div>
            <div class="contact">
                <h3>Contact Us</h3>
                <p>email: talhamumtaz@gmail.com</p>
                <p>address: Jinnah Company, Rawalpindi</p>
            </div>
        </footer> {% endcomment %}
        <script src="{% static 'js.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    </body>
    
</html>

app/templates/app/leaderboard.html
{% extends 'app/layout.html' %}

{% block body %}

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Description</th>
            <th scope="col">Topic</th>
        </tr>
    </thead>
    <tbody>
        {% for i in res %}
        <tr>
            <th scope="row">{{i.0}}</th>
            <td>{{i.1}}</td>
            <td>{{i.6}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

app/templates/app/login.html
{% extends 'app/layout.html' %}

{% block body %}
    {% load static %}

    <div class="container text-center">
        <form action="/app/" method="post">
            {% csrf_token %}
            <img style="border-radius: 3ch" class="mb-4" src="{% static 'pic4.jpg' %}" alt="" width="72" height="57">
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
        
            <div class="form-floating">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
            </div>
        
            <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
        </form>
    </div>
{% endblock %}

app/templates/app/signup.html
{% extends 'app/layout.html' %}

{% block body %}
    <form action="login" method="post" id="myForm">
        {% csrf_token %}

        <section class="pb-4">
            <div class="bg-white border rounded-5">
                
                <section class="w-100 px-4 py-5 bg-dark" style="border-radius: .5rem .5rem 0 0;">
                <style>
                    .card-registration .select-input.form-control[readonly]:not([disabled]) {
                    font-size: 1rem;
                    line-height: 2.15;
                    padding-left: .75em;
                    padding-right: .75em;
                    }
            
                    .card-registration .select-arrow {
                    top: 13px;
                    }
                </style>
                <div class="row">
                    <div class="col">
                    <div class="card card-registration">
                        <div class="row g-0">
                        <div class="col-xl-6 d-none d-xl-block">
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img4.webp" alt="Sample photo" class="img-fluid" style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem;">
                        </div>
                        <div class="col-xl-6">
                            <div class="card-body p-md-5 text-black">
                            <h4 class="mb-5 text-uppercase">Student registration form</h4>
            
                            <div class="row">
                                <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <input type="text" id="form3Example1m" class="form-control form-control-lg">
                                    <label class="form-label" for="form3Example1m" style="margin-left: 0px;">First name</label>
                                <div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 68.8px;"></div><div class="form-notch-trailing"></div></div></div>
                                </div>
                                <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <input type="text" id="form3Example1n" class="form-control form-control-lg">
                                    <label class="form-label" for="form3Example1n" style="margin-left: 0px;">Last name</label>
                                <div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 68px;"></div><div class="form-notch-trailing"></div></div></div>
                                </div>
                            </div>
            
                            <div class="form-outline mb-4">
                                <input type="text" id="form3Example8" class="form-control form-control-lg">
                                <label class="form-label" for="form3Example8" style="margin-left: 0px;">Address</label>
                            <div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 55.2px;"></div><div class="form-notch-trailing"></div></div></div>
            
                            <div class="d-md-flex justify-content-start align-items-center mb-4 py-2">
            
                                <h6 class="mb-0 me-4">Gender: </h6>
            
                                <div class="form-check form-check-inline mb-0 me-4">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="femaleGender" value="option1">
                                <label class="form-check-label" for="femaleGender">Female</label>
                                </div>
            
                                <div class="form-check form-check-inline mb-0 me-4">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="maleGender" value="option2">
                                <label class="form-check-label" for="maleGender">Male</label>
                                </div>
            
                                <div class="form-check form-check-inline mb-0">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="otherGender" value="option3">
                                <label class="form-check-label" for="otherGender">Other</label>
                                </div>
            
                            </div>
            
                            <div class="row">
                                <div class="col-md-6 mb-4">
            
                                <div id="select-wrapper-53891" class="select-wrapper"><div class="form-outline"><input class="form-control select-input placeholder-active active" type="text" role="listbox" aria-multiselectable="false" aria-disabled="false" aria-haspopup="true" aria-expanded="false" readonly="true"><span class="select-arrow"></span><div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 0px;"></div><div class="form-notch-trailing"></div></div><div class="form-label select-fake-value">State</div></div><select class="select select-initialized">
                                    <option value="1">State</option>
                                    <option value="2">Option 1</option>
                                    <option value="3">Option 2</option>
                                    <option value="4">Option 3</option>
                                </select></div>
            
                                </div>
                                <div class="col-md-6 mb-4">
            
                                <div id="select-wrapper-574174" class="select-wrapper"><div class="form-outline"><input class="form-control select-input placeholder-active active" type="text" role="listbox" aria-multiselectable="false" aria-disabled="false" aria-haspopup="true" aria-expanded="false" readonly="true"><span class="select-arrow"></span><div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 0px;"></div><div class="form-notch-trailing"></div></div><div class="form-label select-fake-value">City</div></div><select class="select select-initialized">
                                    <option value="1">City</option>
                                    <option value="2">Option 1</option>
                                    <option value="3">Option 2</option>
                                    <option value="4">Option 3</option>
                                </select></div>
            
                                </div>
                            </div>
            
                            <div class="form-outline mb-4">
                                <input type="text" id="form3Example90" class="form-control form-control-lg">
                                <label class="form-label" for="form3Example90" style="margin-left: 0px;">Pincode</label>
                            <div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 54.4px;"></div><div class="form-notch-trailing"></div></div></div>
            
                            <div class="form-outline mb-4">
                                <input type="text" id="form3Example99" class="form-control form-control-lg">
                                <label class="form-label" for="form3Example99" style="margin-left: 0px;">Course</label>
                            <div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 49.6px;"></div><div class="form-notch-trailing"></div></div></div>
            
                            <div class="form-outline mb-4">
                                <input type="text" id="form3Example97" class="form-control form-control-lg">
                                <label class="form-label" for="form3Example97" style="margin-left: 0px;">Email ID</label>
                            <div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 56px;"></div><div class="form-notch-trailing"></div></div></div>
            
                            <div class="d-flex justify-content-end pt-3">
                                <button type="button" class="btn btn-light btn-lg" onclick="document.getElementById('myForm').reset();">Reset all</button>
                                <button type="submit" class="btn btn-warning btn-lg ms-2">Submit form</button>
                            </div>
            
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                </section>
            </div>
        </section>
    </form>
{% endblock %}

app/templates/app/taskdetails.html
{% extends 'app/layout.html' %}

{% block body %}

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Description</th>
            <th scope="col">Topic</th>
        </tr>
    </thead>
    <tbody>
        {% for i in res %}
        <tr>
            <th scope="row">{{i.0}}</th>
            <td>{{i.1}}</td>
            <td>{{i.6}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

app/templates/app/welcome.html
{% extends 'app/layout.html' %}

{% block body %}
    {% load static %}

    <div class="bg-dark text-secondary px-4 py-5 text-center">
        <div class="py-5">
            <h1 class="display-1 fw-bold text-white">Welcome to TaskHub</h1>
            
            <div class="col-lg-6 mx-auto">
                <p class="fs-5 mb-4">
                    <p class="display-6 fw-bold">What we do...</p>
                    <div id="txt_mid">Apple is a sweet and delicious fruit that is very healthy. It is also a good disease-fighter and we can eat it every day. The delicious taste and bright colour of the food make it even more appealing. Moreover, it is a versatile fruit which we can use in many dishes. In an essay on apple, we will learn how many benefits it offers. You must have heard that “an apple a day, keeps the doctor away.” I remember hearing this for the first time and I decided to eat an apple every day. Ever since it has become my favourite fruit. It is round in shape and comes in a red colour. But, there are also green apples. An apple contains a high quantity of juice which is mixed with high fibres. It tastes sweet and is edible for everyone. As it is one of the healthiest fruit, it is my favourite. I try to eat one every day for the betterment of my health. One single apple contains 130 calories. The insoluble fibre in the fruit is effective for the body because it does not mix with water.</div>
                    <p id="h1_bold">What our users say...</p>
                </p>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                    <a href="app/signup"><button type="button" class="btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold">Sign Up</button></a>
                    <a href="app/login"><button type="button" class="btn btn-outline-light btn-lg px-4">Sign In</button></a>
                </div>
            </div>
        </div>
    </div>

    {% comment %} <h1 class="welcome">Welcome to TaskHub</h1>

    <div>
        <a href="app/signup"><button id='signup'>Sign Up</button></a>
    </div>
    
    <p id="h1_bold">What we do...</p>
    <div id="txt_mid">Apple is a sweet and delicious fruit that is very healthy. It is also a good disease-fighter and we can eat it every day. The delicious taste and bright colour of the food make it even more appealing. Moreover, it is a versatile fruit which we can use in many dishes. In an essay on apple, we will learn how many benefits it offers. You must have heard that “an apple a day, keeps the doctor away.” I remember hearing this for the first time and I decided to eat an apple every day. Ever since it has become my favourite fruit. It is round in shape and comes in a red colour. But, there are also green apples. An apple contains a high quantity of juice which is mixed with high fibres. It tastes sweet and is edible for everyone. As it is one of the healthiest fruit, it is my favourite. I try to eat one every day for the betterment of my health. One single apple contains 130 calories. The insoluble fibre in the fruit is effective for the body because it does not mix with water.</div>
    <p id="h1_bold">What our users say...</p> {% endcomment %}
    {% comment %} <div id="images">
        <img src="{% static 'pic1.png' %}">
    </div>
    Maza aagya!
    
    <div id="images">
        <img src="{% static 'pic2.png' %}">
    </div>
    Boht Boht maja aya!
    
    <div id="images">
        <img src="{% static 'pic3.png' %}">
    </div>
    Dil Garden Garden horya hai! {% endcomment %}
{% endblock %}